version: "3.9"

services:
    app:
        image: "simonesestito/foody:latest"
        ports:
          - "${PORT:-8080}:8080"
        depends_on:
            - db
        
    db:
        image: "yobasystems/alpine-mariadb:10.6.4"
        volumes:
            - db-data:/var/lib/mysql
            - ./db/mariadb-app-settings.cnf:/etc/my.cnf.d/mariadb-app-settings.cnf:ro
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s
        environment:
            MYSQL_ROOT_PASSWORD: pwd
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: pwd

volumes:
    db-data:
