version: "3.9"

services:
    app:
        image: "simonesestito/foody:latest"
        ports:
          - "${DOCKER_HOST_PROXY_PORT:-8080}:5000"
        depends_on:
            - db
        env_file:
            - .env
        deploy:
            restart_policy:
                condition: on-failure
                delay: 1s
        
    db:
        image: "yobasystems/alpine-mariadb:10.6.4"
        volumes:
            - db-data:/var/lib/mysql
            - ./db/mariadb-app-settings.cnf:/etc/my.cnf.d/mariadb-app-settings.cnf:ro
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-pwd}"
            MYSQL_DATABASE: "${MYSQL_DATABASE:-foody}"
            MYSQL_USER: "${MYSQL_USER:-foody}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD:-pwd}"

volumes:
    db-data:
